sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1Shicaomoni
  upload:
    host-path: http://192.168.20.11:8080/images/
    upload-path: /Users/mac/Library/CloudStorage/GoogleDrive-guotaixiao87@gmail.com/My Drive/material/苍穹外卖/material/resourse/资料/day01/后端初始工程/sky-take-out/sky-server/src/main/resources/static/images/
  redis:
    host: localhost
    port: 6379
    password: 1Shicaomoni
    database: 0
  wechat:
    appid: wx67ea3662d2af4260
    secret: 06ab14bdb953fe9e428e8cba5d0ef712